### ISSUE TITLE
Playtesting is saving resource multiple times

### ISSUE THREAD

**Issue by bazsupport** [derkork/godot-resource-groups#4] opened 2024-02-13 20:52 UTC
I'm not sure how or why but whenever I go to playtest, I'm getting multiple savings of the resources:
![Godot_4 2 1_esbswBKg4H](https://github.com/derkork/godot-resource-groups/assets/45674197/a57f28fa-0c41-4725-891c-44ce2dd8b6eb)

It seems like it could be creating a longer delay to get the playtest up and running, feels like it, but not certain.

Forgot to mention, thanks for this awesome plugin!!!!

**Comment by derkork** [comment] 2024-02-14 17:16
The resource-groups will be updated whenever the project is saved and Godot saves the project before every launch of the game. This way it can be ensured that all resource group data is up-to-date with the current project before your game is started. I have tried this on projects with thousands of files and I have not yet encountered any noticable slowdown of the startup procedure. 

One alternative would be that you have to manually update the resource groups when you change something in your project. This could be done with a special menu entry. But I feel this is easy to forget and might cost significant development time in chasing down "bugs" which were caused by forgetting to update the resource groups. 

What are your thoughts on this?

**Comment by bazsupport** [comment] 2024-02-14 17:44
I actually don't mind the current way you have it automated, I was mostly curious why it saves so many times on playtest?

That image you see with the 8 print outs was after pressing playtest, not manual saves. I average about 2-5 of those messages per playtest. So my thought was maybe it's running more then it needed to?

**Comment by derkork** [comment] 2024-02-14 17:56
Hmm that is odd indeed. The plugin reacts to the `_save_external_data` call from the godot editor, so if this appearing 2 to 5 times then it is because the editor calls it that often. Now the interesting part would be why does the editor call it this often when you play the game? Are you using other plugins or custom scripts that run or do you manybe press Ctrl+S a lot?

**Comment by bazsupport** [comment] 2024-02-14 18:28
I do press Ctrl+ S a lot, as much as I can anyway cause I'm afraid of the Godot editor still lol.
But all those prints are after a playtest is clicked, because it clears the output area and puts all the prints.
Here is a gif of me clicking playest:
![Godot_4 2 1_q7qxy8mg8t](https://github.com/derkork/godot-resource-groups/assets/45674197/3164c772-df1f-4e1e-a4de-2876a1c1c140)

Here is plugin list:
![Godot_4 2 1_32VOdTpOLI](https://github.com/derkork/godot-resource-groups/assets/45674197/776d7c6e-377c-4a5a-8148-55b2dcadc8f4)

**Comment by BadBoyGodot** [comment] 2024-02-15 06:15
I did some searching and it's a known issue here https://github.com/godotengine/godot/issues/29468.

seems like if put print() in _save_external_data() it will definitely print multiple times.

**Comment by bazsupport** [comment] 2024-02-15 15:41
> seems like if put print() in _save_external_data() it will definitely print multiple times when click "Run" in editor.

Ok so it's only printing that much, it's not actually resaving a bunch?

**Comment by derkork** [comment] 2024-02-15 16:20
It _is_ resaving stuff multiple times when being called multiple times. As a workaround the plugin could maybe remember the last time it resaved and if its only a few milliseconds away doesn't do it. Would be nicer if the underlying issue was fixed though.

**Comment by lukasmakegames** [comment] 2024-02-16 07:34
Hello I am having the same issue, takes a long to play testing, but I think is a kind of bug, because I have moved the resource group and deleted it then created a new one and the deleted is still trying to access the base folder files, just the last one is correct 
![image](https://github.com/derkork/godot-resource-groups/assets/58825785/218c41ce-068d-4a98-971a-d764c77e2738)

**Comment by derkork** [comment] 2024-02-16 13:03
I tried moving it into the `_build` function which fixes the problem when running but because `_build` is not run on export it could happen that you export the last state that you ran rather than what is actually inside of the resource groups...

**Comment by derkork** [comment] 2024-07-19 12:40
The exporting problem could be addressed with an [EditorExportPlugin](https://docs.godotengine.org/en/stable/classes/class_editorexportplugin.html#class-editorexportplugin).

**Closed** 2024-07-19 14:52 UTC
Labels: question
